project:
  type: website

website:
  site-url: https://stat210a.berkeley.edu/fall-2024/
  google-analytics: G-B8G2041HSB
  sidebar:
    style: docked
    title: "Ajay Sharma"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/ajay8005
      - icon: linkedin
        href: https://linkedin.com/in/asharma2718
    contents:
      - href: index.qmd
        text: About Me
      - href: resume.qmd
      - section: "Projects"
        contents:
          - webapp.qmd
          - projects.qmd
          - book.qmd
      - section: "Berkeley Coursework"
        contents:
          - berkeley-coursework.qmd
          - homework-solutions.qmd
      - href: contact.qmd
        text: "Contact & Tutoring Services"
      - href: license.qmd
        text: License

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      - file: siteimprove.html
      - |
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
